name: HK Stock Bot
on:
  schedule:
    - cron: '35 1 * * 1-5'
  workflow_dispatch:
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install yfinance pandas requests
      - run: python hkbot_fill.py
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
